"""
Structured Observation Model for ChakrView Cognitive Subsystem (Step 15).

Captures empirical outputs, timing, provenance, and verification outcomes
following step execution.
"""

from dataclasses import dataclass, field, asdict
import time
from typing import Dict, List, Optional, Any


@dataclass
class StepObservation:
    """
    Structured outcome of an individual cognitive step execution.

    Attributes:
        step_id: Identifier of the step that produced this observation.
        success: Whether the underlying execution succeeded.
        output: Raw or structured result generated by the step.
        error: Diagnostic error message if failed.
        execution_time_ms: Wall-clock duration of step execution.
        provenance: References to data sources, tool IDs, or memory IDs involved.
        verification_status: Whether the observation satisfied verification checks.
        verification_notes: Diagnostic rationale from the verifier.
        created_at: Epoch timestamp of creation.
    """
    step_id: str
    success: bool
    output: Any = None
    error: Optional[str] = None
    execution_time_ms: float = 0.0
    provenance: Dict[str, Any] = field(default_factory=dict)
    verification_status: bool = True
    verification_notes: str = ""
    created_at: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize observation to structured dictionary."""
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "StepObservation":
        """Deserialize observation from structured dictionary."""
        return cls(**data)
