"""
ChakrView Step 59/60: Repository Cognition Package Exports.
"""

from chakrview.cognition.repository.inspector import RepositoryInspector, ModuleInspection
from chakrview.cognition.repository.graph import RepositoryDependencyGraph, DependencyEdge
from chakrview.cognition.repository.planner import (
    RepositoryActionType,
    RepositoryAction,
    RepositoryObservation,
    RepositoryDiagnosis,
    RepositoryPlan,
)
from chakrview.cognition.repository.patch import (
    MultiFilePatchTransaction,
    RepositoryPatchCoordinator,
)
from chakrview.cognition.repository.verifier import (
    RepositoryVerificationResult,
    RepositoryVerifier,
)
from chakrview.cognition.repository.engine import RepositoryCognitionEngine
from chakrview.cognition.repository.semantic_record import RepositorySemanticRecord
from chakrview.cognition.repository.memory_index import RepositoryMemoryIndex
from chakrview.cognition.repository.arbitration import (
    ArbitrationWeights,
    DEFAULT_WEIGHTS,
    RepositoryQuery,
    ArbitrationSignalBreakdown,
    ArbitrationCandidate,
    ArbitrationStatus,
    ArbitrationResult,
    arbitrate,
)
from chakrview.cognition.repository.state import FileState, RepositoryState
from chakrview.cognition.repository.change_detector import (
    ChangeCategory,
    FileChange,
    RepositoryDiff,
    RepositoryChangeDetector,
)
from chakrview.cognition.repository.impact_analyzer import (
    MemoryValidityStatus,
    MemoryRevalidationDecision,
    ImpactReport,
    RepositoryImpactAnalyzer,
)
from chakrview.cognition.repository.refactoring import (
    RefactoringStep,
    RefactoringPlan,
    StepExecutionResult,
    MultiStepRefactoringResult,
    MultiStepRefactoringCoordinator,
)
from chakrview.cognition.repository.branching import (
    BranchStatus,
    RefactoringBranch,
    BranchObservation,
    BranchSelectionDecision,
    RecoveryDecision,
    BranchingRefactoringResult,
    ObservationDrivenBranchingCoordinator,
)
from chakrview.cognition.repository.synthesis import (
    CandidateOrigin,
    SafetyDecision,
    CandidateProvenance,
    SynthesizedCandidate,
    NormalizationResult,
    CandidateNormalizer,
    SafetyGateDecision,
    DeterministicSafetyGate,
    CandidateDeduplicator,
    StrategyRecombiner,
    CandidateSynthesisEngine,
    DeterministicRuleSynthesisEngine,
    SynthesisCoordinationResult,
    SynthesisAwareBranchingCoordinator,
)
from chakrview.cognition.repository.context_store import (
    EpistemicState,
    EvidenceRecord,
    CachedFileEntry,
    ContextStoreTelemetry,
    RepositoryContextStore,
    GroundedContextBudget,
    GroundedContextBundle,
    GroundedContextRetriever,
)
from chakrview.cognition.repository.neural_adapter import (
    NeuralProposalOutput,
    NeuralProposalAdapter,
    GroundingVerificationDecision,
    HallucinationContainmentGate,
    GroundedNeuralSynthesisEngine,
)
from chakrview.cognition.repository.episodic_learning import (
    EpisodeOutcome,
    FailureClass,
    AdmissionStatus,
    LearnedObservation,
    EpisodicExperience,
    AdmissionDecision,
    DeterministicAdmissionGate,
    EpisodicLearningCoordinator,
)
from chakrview.cognition.repository.episodic_recall import (
    MemoryRecallStatus,
    MemoryRecallRequest,
    RecallBudget,
    RecalledMemoryItem,
    RecalledContextBundle,
    EpisodicMemoryRecallCoordinator,
)
from chakrview.cognition.repository.cognitive_context import (
    CognitiveContextSource,
    CognitiveContextStatus,
    CognitiveContextBudget,
    CognitiveContextRequest,
    CognitiveContextItem,
    CognitiveContextTelemetry,
    CognitiveContextBundle,
    UnifiedCognitiveContextComposer,
)
from chakrview.cognition.repository.neural_proposal import (
    ProposalValidationStatus,
    EpistemicPartition,
    StructuredEpistemicClaim,
    ProposalContract,
    NeuralProposalInputEncoder,
    ProposalValidator,
    ChakrMicroNeuralProposalAdapter,
)
from chakrview.cognition.repository.patch_planning import (
    PatchOperationType,
    PatchPlanStatus,
    PatchOperation,
    PatchPlan,
    PatchPlanner,
    PatchPlanValidator,
    generate_deterministic_diff,
    sanitize_relative_path,
)
from chakrview.cognition.repository.patch_execution import (
    PatchExecutionStatus,
    PatchExecutionRequest,
    PatchRollbackRecord,
    PatchExecutionResult,
    SafePatchExecutor,
)
from chakrview.cognition.ppb import (
    CURRENT_SCHEMA_VERSION,
    EpistemicStatus,
    KnowledgeRecordType,
    KnowledgeRecord,
    ProjectIdentity,
    ProjectBrainState,
    PPBStorageSchemaError,
    PersistentBrainStorage,
    PersistentProjectBrain,
    ScanBatchProgress,
    IncrementalProjectScanner,
    PPBRetrievalBudget,
    RetrievedKnowledgeBundle,
    ProjectKnowledgeRetriever,
    MaintenanceReport,
    ChangeAwareBrainMaintainer,
)

__all__ = [

    "RepositoryInspector",
    "ModuleInspection",
    "RepositoryDependencyGraph",
    "DependencyEdge",
    "RepositoryActionType",
    "RepositoryAction",
    "RepositoryObservation",
    "RepositoryDiagnosis",
    "RepositoryPlan",
    "MultiFilePatchTransaction",
    "RepositoryPatchCoordinator",
    "RepositoryVerificationResult",
    "RepositoryVerifier",
    "RepositoryCognitionEngine",
    "RepositorySemanticRecord",
    "RepositoryMemoryIndex",
    "ArbitrationWeights",
    "DEFAULT_WEIGHTS",
    "RepositoryQuery",
    "ArbitrationSignalBreakdown",
    "ArbitrationCandidate",
    "ArbitrationStatus",
    "ArbitrationResult",
    "arbitrate",
    "FileState",
    "RepositoryState",
    "ChangeCategory",
    "FileChange",
    "RepositoryDiff",
    "RepositoryChangeDetector",
    "MemoryValidityStatus",
    "MemoryRevalidationDecision",
    "ImpactReport",
    "RepositoryImpactAnalyzer",
    "RefactoringStep",
    "RefactoringPlan",
    "StepExecutionResult",
    "MultiStepRefactoringResult",
    "MultiStepRefactoringCoordinator",
    "BranchStatus",
    "RefactoringBranch",
    "BranchObservation",
    "BranchSelectionDecision",
    "RecoveryDecision",
    "BranchingRefactoringResult",
    "ObservationDrivenBranchingCoordinator",
    "CandidateOrigin",
    "SafetyDecision",
    "CandidateProvenance",
    "SynthesizedCandidate",
    "NormalizationResult",
    "CandidateNormalizer",
    "SafetyGateDecision",
    "DeterministicSafetyGate",
    "CandidateDeduplicator",
    "StrategyRecombiner",
    "CandidateSynthesisEngine",
    "DeterministicRuleSynthesisEngine",
    "SynthesisCoordinationResult",
    "SynthesisAwareBranchingCoordinator",
    "EpistemicState",
    "EvidenceRecord",
    "CachedFileEntry",
    "ContextStoreTelemetry",
    "RepositoryContextStore",
    "GroundedContextBudget",
    "GroundedContextBundle",
    "GroundedContextRetriever",
    "NeuralProposalOutput",
    "NeuralProposalAdapter",
    "MockNeuralProposalAdapter",
    "GroundingVerificationDecision",
    "HallucinationContainmentGate",
    "GroundedNeuralSynthesisEngine",
    "EpisodeOutcome",
    "FailureClass",
    "AdmissionStatus",
    "LearnedObservation",
    "EpisodicExperience",
    "AdmissionDecision",
    "DeterministicAdmissionGate",
    "EpisodicLearningCoordinator",
    "MemoryRecallStatus",
    "MemoryRecallRequest",
    "RecallBudget",
    "RecalledMemoryItem",
    "RecalledContextBundle",
    "EpisodicMemoryRecallCoordinator",
    "CognitiveContextSource",
    "CognitiveContextStatus",
    "CognitiveContextBudget",
    "CognitiveContextRequest",
    "CognitiveContextItem",
    "CognitiveContextTelemetry",
    "CognitiveContextBundle",
    "UnifiedCognitiveContextComposer",
    "ProposalValidationStatus",
    "EpistemicPartition",
    "StructuredEpistemicClaim",
    "ProposalContract",
    "NeuralProposalInputEncoder",
    "ProposalValidator",
    "ChakrMicroNeuralProposalAdapter",
    "PatchOperationType",
    "PatchPlanStatus",
    "PatchOperation",
    "PatchPlan",
    "PatchPlanner",
    "PatchPlanValidator",
    "generate_deterministic_diff",
    "sanitize_relative_path",
    "PatchExecutionStatus",
    "PatchExecutionRequest",
    "PatchRollbackRecord",
    "PatchExecutionResult",
    "SafePatchExecutor",
    "CURRENT_SCHEMA_VERSION",
    "EpistemicStatus",
    "KnowledgeRecordType",
    "KnowledgeRecord",
    "ProjectIdentity",
    "ProjectBrainState",
    "PPBStorageSchemaError",
    "PersistentBrainStorage",
    "PersistentProjectBrain",
    "ScanBatchProgress",
    "IncrementalProjectScanner",
    "PPBRetrievalBudget",
    "RetrievedKnowledgeBundle",
    "ProjectKnowledgeRetriever",
    "MaintenanceReport",
    "ChangeAwareBrainMaintainer",
]



